### ISSUE TITLE
Dependency issue

### ISSUE THREAD

**Issue by frash83** [ducha-aiki/manifold-diffusion#1]
Hello,

There are a lot of libraries that cannot be "pip install ..." such as:

from dataset import configdataset
from download import download_datasets, download_features
from evaluate import compute_map

Could you please help to run the code?

**Comment by ducha-aiki** [comment]
Hi,

As stated in Readme.MD, example works only with https://github.com/filipradenovic/revisitop  benchmark

> Example of usage: copy files into python directory of the RevisitOP benchmark and run

The code for diffusion (diffussion.py)  does not depend on revisitop repo, but evaluation script (example_evaluate_with_diff.py) does.
